name: Build fcrypt docker image
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup jdk 22
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 22

      - name: Unit tests
        run: mvn -B test --file pom.xml

  build:
    name: Push fcrypt docker image to docker hub
    runs-on: ubuntu-22.04
    needs: tests
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup jdk 22
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 22

      - name: Build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Confirm git commit SHA output
        run: echo ${{ env.COMMIT_SHORT_SHA }}

      - name: Build the docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fcrypt:${{ env.COMMIT_SHORT_SHA }}

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push the docker image to docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fcrypt:${{ env.COMMIT_SHORT_SHA }}
