name: build fcrypt docker image
on:
  push:
    branches:
      - main

jobs:
  build:
    name: push fcrypt docker image to docker hub
    runs-on: ubuntu-22.04
    needs: tests
    if: success()
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup jdk 22
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 22

      - name: build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: build the docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fcrypt:$(git rev-parse --short HEAD)

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push the docker image to docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fcrypt:$(git rev-parse --short HEAD)
